<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PrescriptionOrder extends Model
{
    protected $fillable = [
        'order_id',
        'images',
        'action_id',
        'duration'
    ];

    protected $casts = [
        'created_at' => 'date',
        'images' => 'json'
    ];

    public $timestamps = false;


    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($model) {
            $model->created_at = $model->freshTimestamp();
        });
    }

    public function order()
    {
        $this->belongsTo('App\Order');
    }
}
